#!/usr/bin/env bash
#==============================================================================
# WAES Markdown Exporter
# Export scan results to Markdown format for documentation
#==============================================================================

set -euo pipefail

# Generate Markdown report
export_to_markdown() {
    local target="$1"
    local report_dir="${2:-.}"
    local scan_type="${3:-full}"
    local output_file="${4:-${report_dir}/${target}_report.md}"
    
    local scan_date
    scan_date=$(date '+%Y-%m-%d %H:%M:%S')
    
    {
        echo "# WAES Security Scan Report"
        echo ""
        echo "**Target:** $target"
        echo "**Scan Type:** $scan_type"
        echo "**Date:** $scan_date"
        echo ""
        echo "---"
        echo ""
        
        # Nmap results
        if [[ -f "${report_dir}/${target}_nmap_standard.nmap" ]]; then
            echo "## Open Ports"
            echo ""
            echo "| Port | State | Service | Version |"
            echo "|------|-------|---------|---------|"
            
            grep -E "^[0-9]+/tcp" "${report_dir}/${target}_nmap_standard.nmap" | while read -r line; do
                local port state service version
                port=$(echo "$line" | awk '{print $1}')
                state=$(echo "$line" | awk '{print $2}')
                service=$(echo "$line" | awk '{print $3}')
                version=$(echo "$line" | cut -d' ' -f4-)
                
                echo "| $port | $state | $service | ${version:-N/A} |"
            done
            echo ""
        fi
        
        # SSL findings
        if [[ -f "${report_dir}/${target}_ssl_scan.txt" ]]; then
            echo "## SSL/TLS Findings"
            echo ""
            grep -i "vulnerable\|weak\|insecure" "${report_dir}/${target}_ssl_scan.txt" | while read -r finding; do
                echo "- ⚠️  $finding"
            done
            echo ""
        fi
        
        # CMS detection
        if [[ -f "${report_dir}/${target}_cms_scan.txt" ]]; then
            echo "## CMS Detection"
            echo ""
            if grep -qi "wordpress" "${report_dir}/${target}_cms_scan.txt"; then
                echo "- **CMS:** WordPress"
            elif grep -qi "drupal" "${report_dir}/${target}_cms_scan.txt"; then
                echo "- **CMS:** Drupal"
            elif grep -qi "joomla" "${report_dir}/${target}_cms_scan.txt"; then
                echo "- **CMS:** Joomla"
            else
                echo "- No CMS detected"
            fi
            echo ""
        fi
        
        # Recommendations
        echo "## Recommendations"
        echo ""
        echo "1. Review and patch all identified vulnerabilities"
        echo "2. Disable unnecessary services"
        echo "3. Implement strong SSL/TLS configuration"
        echo "4. Keep CMS and plugins updated"
        echo "5. Implement WAF and monitoring"
        echo ""
        
        echo "---"
        echo "*Generated by WAES v1.2.0*"
    } > "$output_file"
    
    echo "[+] Markdown report generated: $output_file"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    export_to_markdown "$@"
fi
