#!/usr/bin/env bash
#==============================================================================
# WAES Report Cleaner
# Safely manages report directory files
#==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
REPORT_DIR="${ROOT_DIR}/report"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

#==============================================================================
# FUNCTIONS
#==============================================================================

usage() {
    cat << EOF
Usage: ${0##*/} [OPTIONS]

Clean up report files generated by WAES

Options:
    -a, --archive   Archive files before deletion (creates .tar.gz)
    -d, --days N    Only delete files older than N days
    -f, --force     Skip confirmation prompt
    -n, --dry-run   Show what would be deleted without removing
    -h, --help      Show this help

Examples:
    ${0##*/}                    # Interactive cleanup
    ${0##*/} -a                 # Archive before deleting
    ${0##*/} -d 7               # Delete files older than 7 days
    ${0##*/} -f                 # Force delete without confirmation
EOF
    exit 0
}

log_info() {
    echo -e "${BLUE}[*]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[+]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[~]${NC} $*"
}

log_error() {
    echo -e "${RED}[!]${NC} $*" >&2
}

count_files() {
    find "$REPORT_DIR" -maxdepth 1 -type f 2>/dev/null | wc -l
}

get_total_size() {
    du -sh "$REPORT_DIR" 2>/dev/null | cut -f1
}

list_files() {
    local days="${1:-0}"
    
    if [[ $days -gt 0 ]]; then
        find "$REPORT_DIR" -maxdepth 1 -type f -mtime +"$days" -exec ls -lh {} \;
    else
        find "$REPORT_DIR" -maxdepth 1 -type f -exec ls -lh {} \;
    fi
}

archive_reports() {
    local archive_name="waes_reports_$(date +%Y%m%d_%H%M%S).tar.gz"
    local archive_path="${SCRIPT_DIR}/${archive_name}"
    
    log_info "Creating archive: $archive_name"
    
    if tar -czf "$archive_path" -C "$REPORT_DIR" . 2>/dev/null; then
        log_success "Archive created: $archive_path"
        return 0
    else
        log_error "Failed to create archive"
        return 1
    fi
}

delete_files() {
    local days="${1:-0}"
    
    if [[ $days -gt 0 ]]; then
        find "$REPORT_DIR" -maxdepth 1 -type f -mtime +"$days" -delete
    else
        find "$REPORT_DIR" -maxdepth 1 -type f -delete
    fi
}

#==============================================================================
# MAIN
#==============================================================================

main() {
    local archive=false
    local days=0
    local force=false
    local dry_run=false
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -a|--archive)
                archive=true
                shift
                ;;
            -d|--days)
                days="$2"
                shift 2
                ;;
            -f|--force)
                force=true
                shift
                ;;
            -n|--dry-run)
                dry_run=true
                shift
                ;;
            -h|--help)
                usage
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                ;;
        esac
    done
    
    # Check if report directory exists
    if [[ ! -d "$REPORT_DIR" ]]; then
        log_error "Report directory not found: $REPORT_DIR"
        exit 1
    fi
    
    # Count files
    local file_count
    file_count=$(count_files)
    
    if [[ $file_count -eq 0 ]]; then
        log_info "Report directory is already empty"
        exit 0
    fi
    
    # Show what will be affected
    echo ""
    log_info "Report directory: $REPORT_DIR"
    log_info "Total files: $file_count"
    log_info "Total size: $(get_total_size)"
    
    if [[ $days -gt 0 ]]; then
        log_info "Filtering: files older than $days days"
    fi
    
    echo ""
    echo "Files to be deleted:"
    echo "--------------------"
    list_files "$days"
    echo ""
    
    # Dry run mode
    if [[ "$dry_run" == "true" ]]; then
        log_warn "Dry run mode - no files were deleted"
        exit 0
    fi
    
    # Confirmation
    if [[ "$force" != "true" ]]; then
        read -rp "Are you sure you want to delete these files? [y/N]: " response
        response="${response,,}"  # Convert to lowercase
        
        if [[ ! "$response" =~ ^(yes|y)$ ]]; then
            log_info "Aborted"
            exit 0
        fi
    fi
    
    # Archive if requested
    if [[ "$archive" == "true" ]]; then
        if ! archive_reports; then
            log_error "Archive failed. Aborting deletion."
            exit 1
        fi
    fi
    
    # Delete files
    log_info "Deleting files..."
    delete_files "$days"
    
    log_success "Cleanup complete!"
    log_info "Remaining files: $(count_files)"
}

main "$@"
